# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macOS-11'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'src/UITestDemo.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: 'Xamarin.UITest/**/UITestDemo.Droid.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'ls -la src/UITestDemo/packages'

- task: AppCenterTest@1
  inputs:
    appFile: '$(outputDirectory)/**/com.appcenter.UITestDemo.apk'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    frameworkOption: 'uitest'
    uiTestBuildDirectory: 'src/UITestDemo.UITest'
    credentialsOption: 'serviceEndpoint'
    serverEndpoint: 'appcenter'
    appSlug: 'lekkion/test-android'
    devices: 'lekkion/phones'
    localeOption: 'en_US'
    skipWaitingForResults: true
    showDebugOutput: true
